#!/usr/bin/env bash

export P2_ARCHIVE=$(find ./cucumber.eclipse.p2updatesite/target -name "*.zip")

VERSION=$(echo $P2_ARCHIVE | sed 's#.*cucumber-eclipse-plugin-\(.*\)\(-SNAPSHOT\)\?\.zip#\1#')

if [[ "$VERSION" == *"SNAPSHOT"* ]] ; then
  VERSION=${VERSION/-SNAPSHOT/}
  PRERELEASE="$(date '+%Y%m%d%H%M%S')"
  export TRAVIS_TAG=${TRAVIS_TAG:-"$VERSION-$PRERELEASE.$TRAVIS_BUILD_NUMBER"}
else
  export TRAVIS_TAG=${TRAVIS_TAG:-"$VERSION"}
fi

export BUILD_DATE="$(date '+%Y-%m-%d %H:%M:%S')"

export DESCRIPTION="$(echo "snapshot "$TRAVIS_TAG"<br/>"$( git log --pretty="format:<font color="#D4AC0D">%h</font>&nbsp;%s<br/>" $TRAVIS_COMMIT_RANGE ) )"
