name: deploy cucumber-eclipse plugin (latest)

on:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: deploy-cucumber-eclipse-plugin

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        path: code
        persist-credentials: false
    - name: Checkout pages
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        path: gh-pages
        ref: gh-pages
        # Credentials are needed to push GitHub pages.
        persist-credentials: true
    - name: Set up JDK
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        java-version: '21'
        distribution: 'adopt'
        architecture: 'x64'
    - name: Build with Maven
      working-directory: code
      run: mvn --batch-mode package
    - name: Deploy to GitHub Pages
      working-directory: gh-pages
      run: |
        mkdir -p update-site/${GITHUB_REF##*/}/
        cp -R ../code/io.cucumber.eclipse.updatesite/target/repository/* update-site/${GITHUB_REF##*/}/
        git add .
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -F - <<EOF 
        Add latest update-site for version ${GITHUB_REF##*/}" -m "Created from ${{ github.sha }}"
        git push origin gh-pages
