name: cucumber-eclipse plugin (latest)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        path: code
    - name: Checkout pages
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        path: gh-pages
        ref: gh-pages
      if: github.event_name != 'pull_request'
    - name: Set up JDK
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        java-version: '21'
        distribution: 'adopt'
        architecture: 'x64'
        cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@12eb41b233df95d49b0c11fc1b5bc8312e5d4ce0 # v5.1
      with:
        maven-version: 3.9.9
    - name: Build with Maven
      working-directory: code
      run: mvn -B package --file pom.xml
    - name: deploy
      working-directory: gh-pages
      run: |
        mkdir -p update-site/${GITHUB_REF##*/}/
        cp -R ../code/io.cucumber.eclipse.updatesite/target/repository/* update-site/${GITHUB_REF##*/}/
        git add .
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "Add latest update-site for version ${GITHUB_REF##*/}"
        git push origin gh-pages --force
      if: github.event_name != 'pull_request'

