name: test cucumber-eclipse plugin

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Set up JDK
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
      with:
        java-version: '21'
        distribution: 'adopt'
        architecture: 'x64'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode package
